# Generated by Django 5.1.2 on 2024-11-02 03:31

import django.db.models.deletion
from django.db import migrations, models


def add_initial_data(apps, schema_editor):
    # Get models from the historical version
    ProjectElement = apps.get_model('projects', 'ProjectElement')
    Material = apps.get_model('projects', 'Material')

    # Create Project Elements
    framing = ProjectElement.objects.create(name="Framing")
    window_door_installation = ProjectElement.objects.create(name="Window and Door Installation")
    electrical = ProjectElement.objects.create(name="Electrical")
    plumbing = ProjectElement.objects.create(name="Plumbing")

    # Create Materials for each Project Element
    Material.objects.create(name="Exterior Wall Framing", project_elemeent=framing)
    Material.objects.create(name="Roof Framing", project_element=framing)
    Material.objects.create(name="Barn Door", project_element=window_door_installation)
    Material.objects.create(name="Shower Fixture", project_element=plumbing)
    Material.objects.create(name="Toilet Installation", project_element=plumbing)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.projectelement')),
            ],
        ),
        migrations.RunPython(add_initial_data),
    ]
