# Generated by Django 5.1.2 on 2024-11-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_quotationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material'),
        ),
    ]
