# Generated by Django 5.1.2 on 2024-11-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_quotationrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projectelement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectelement',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
