# Generated by Django 5.1.2 on 2024-11-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_material_price_projectelement_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
