# Generated by Django 5.1.2 on 2024-11-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_material_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
