# Generated by Django 5.1.2 on 2024-11-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_quotationrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
