# Generated by Django 5.1.2 on 2024-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_quotationrequest_area_size_quotationrequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
