# Generated by Django 5.1.2 on 2024-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_material_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Admin', 'Approved by Admin'), ('Declined by Admin', 'Declined by Admin'), ('Declined by User', 'Declined by User'), ('Complete', 'Complete'), ('Approved by User', 'Approved by User')], default='Pending', max_length=20),
        ),
    ]
