# Generated by Django 5.1.2 on 2024-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_quotationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequest',
            name='project_element',
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='project_element',
            field=models.ManyToManyField(to='projects.projectelement'),
        ),
    ]
