# Generated by Django 5.1.2 on 2024-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_quotationrequest_project_element_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequest',
            name='material',
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='material',
            field=models.ManyToManyField(blank=True, to='projects.material'),
        ),
    ]
